apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: faro-landing
  namespace: faro-landing-development
spec:
  ingressClassName: traefik
  rules:
    - host: faro-landing-development-1.faro.run
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: faro-landing
                port:
                  number: 80
