apiVersion: v1
kind: Service
metadata:
  name: payments
  namespace: payments-development
  labels:
    app.kubernetes.io/managed-by: faro
    app: payments
spec:
  selector:
    app: payments
  ports:
    - port: 80
      targetPort: 8080
