apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: beep-schedule
  namespace: beep-schedule-development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beep-schedule
  template:
    metadata:
      labels:
        app: beep-schedule
    spec:
      containers:
        - name: beep-schedule
          image: 104.248.9.67:5000/beep-schedule:master-346d0fb-v.1
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
              ephemeral-storage: 1Gi
            limits:
              cpu: 1
              memory: 1Gi
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: beep-schedule-development-config
                  key: SPRING__PROFILES__ACTIVE
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: beep-schedule-development-secrets
                  key: JWT__SECRET
            - name: API_KEY_INTERNAL
              valueFrom:
                secretKeyRef:
                  name: beep-schedule-development-secrets
                  key: API__KEY__INTERNAL
            - name: API_KEY_EXTERNAL
              valueFrom:
                secretKeyRef:
                  name: beep-schedule-development-secrets
                  key: API__KEY__EXTERNAL
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: beep-schedule-development-secrets
                  key: DB__URL
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: beep-schedule-development-secrets
                  key: DB__USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: beep-schedule-development-secrets
                  key: DB__PASSWORD
            - name: MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: beep-schedule-development-secrets
                  key: MAIL__USERNAME
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: beep-schedule-development-secrets
                  key: MAIL__PASSWORD
      nodeSelector:
        workload: "mitcr-apps"
      tolerations:
        - key: "workload"
          operator: "Equal"
          value: "mitcr-apps"
          effect: "NoSchedule"
  strategy:
    canary: {}
