apiVersion: v1
kind: Service
metadata:
  name: beep-schedule
  namespace: beep-schedule-development
  labels:
    app.kubernetes.io/managed-by: faro
    app: beep-schedule
spec:
  selector:
    app: beep-schedule
  ports:
    - port: 80
      targetPort: 8080
