apiVersion: v1
kind: Service
metadata:
  name: beep-business
  namespace: beep-business-development
  labels:
    app.kubernetes.io/managed-by: faro
    app: beep-business
spec:
  selector:
    app: beep-business
  ports:
    - port: 80
      targetPort: 8080
